image: python:3.12-slim

stages:
  - linting
  - type-checking
  - testing

.base:
  tags:
    - docker
  before_script:
    - pip install poetry
    - cd flow_selection_service
    - poetry install --no-root
  rules:
    # first match wins
    - changes:
        - "**/*.py"
        - ".gitlab-ci.yml"
        - "poetry.lock"
      when: on_success
    - changes:
        - "**.md"
      when: never
    - when: never

lint_job:
  extends: .base
  stage: linting
  script:
    - poetry run ruff check .

mypy_job:
  extends: .base
  stage: type-checking
  script:
    - poetry run mypy .

testing_job:
  extends: .base
  stage: testing
  script:
    - poetry run pytest -v --tb=short
  coverage: '/TOTAL.*\s+(\d+%)$/'

cache:
  key:
    files:
      - poetry.lock
    prefix: "$CI_COMMIT_REF_SLUG"
  paths:
    - /root/.cache/pypoetry
    - /root/.cache/pip

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"
      when: always
