image: python:3.12-slim

stages:
  - build

.base:
  tags:
    - docker
  before_script:
    - cd $SERVICE
    - pip install poetry
    - export PYTHONPATH="$(pwd)/src"
    - poetry install --no-root
  cache:
    key:
      files:
        - $SERVICE/poetry.lock
    paths:
      - /root/.cache/pypoetry
      - /root/.cache/pip
  rules:
    - changes:
        - "**/*.py"
        - ".gitlab-ci.yml"
        - "$SERVICE/poetry.lock"
      when: on_success
    - changes:
        - "**.md"
      when: never
    - when: never

build_docker_images:
  stage: build
  image: docker:27.0.3
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  parallel:
    matrix:
      - SERVICE: flow-selection-service
      - SERVICE: scoring-service
      - SERVICE: user-data-service
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -f $SERVICE/Dockerfile -t $CI_REGISTRY_IMAGE/$SERVICE:$CI_COMMIT_SHORT_SHA $SERVICE
    - docker push $CI_REGISTRY_IMAGE/$SERVICE:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE/$SERVICE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/$SERVICE:latest
    - docker push $CI_REGISTRY_IMAGE/$SERVICE:latest
  rules:
    - changes:
        - "$SERVICE/**"
        - ".gitlab-ci.yml"
      when: on_success
    - when: never

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"
      when: always

