image: python:3.12-slim

stages:
  - linting
  - type-checking
  - testing
  - build

.base:
  tags:
    - docker
  before_script:
    - cd $SERVICE
    - pip install poetry
    - export PYTHONPATH="$(pwd)/src"
    - poetry install --no-root
  cache:
    key:
      files:
        - $SERVICE/poetry.lock
    paths:
      - /root/.cache/pypoetry
      - /root/.cache/pip
  rules:
    - changes:
        - "**/*.py"
        - ".gitlab-ci.yml"
        - "$SERVICE/poetry.lock"
      when: on_success
    - changes:
        - "**.md"
      when: never
    - when: never

lint_job:
  extends: .base
  stage: linting
  parallel:
    matrix:
      - SERVICE: flow-selection-service
      - SERVICE: scoring-service
      - SERVICE: user-data-service
  script:
    - poetry run ruff check .

mypy_job:
  extends: .base
  stage: type-checking
  parallel:
    matrix:
      - SERVICE: flow-selection-service
      - SERVICE: scoring-service
      - SERVICE: user-data-service
  script:
    - poetry run mypy .

services:
  - name: postgres:17-alpine
    alias: postgres-test
    variables:
      POSTGRES_PASSWORD: postgres_test_password
      POSTGRES_USER: postgres_test_user
      POSTGRES_DB: postgres_test_db

test_job:
  extends: .base
  stage: testing
  parallel:
    matrix:
      - SERVICE: flow-selection-service
      - SERVICE: scoring-service
      - SERVICE: user-data-service
  variables:
    POSTGRES_TEST_HOST: postgres-test
    POSTGRES_TEST_USER: postgres_test_user
    POSTGRES_TEST_PASSWORD: postgres_test_password
    POSTGRES_TEST_DB: postgres_test_db
    POSTGRES_TEST_PORT: 5432
    
  script:
    - poetry run pytest -v --tb=short
  coverage: '/TOTAL.*\s+(\d+%)$/'

build_docker_images:
  stage: build
  image: docker:27.0.3
  services:
    - docker:dind
  parallel:
    matrix:
      - SERVICE: flow-selection-service
      - SERVICE: scoring-service
      - SERVICE: user-data-service
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -f $SERVICE/Dockerfile -t $CI_REGISTRY_IMAGE/$SERVICE:$CI_COMMIT_SHORT_SHA $SERVICE
    - docker push $CI_REGISTRY_IMAGE/$SERVICE:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE/$SERVICE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/$SERVICE:latest
    - docker push $CI_REGISTRY_IMAGE/$SERVICE:latest
  rules:
    - changes:
        - "$SERVICE/**"
        - ".gitlab-ci.yml"
      when: on_success
    - when: never

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"
      when: always

