image: python:3.12-slim

stages:
  - linting
  - type-checking
  - testing

.base:
  tags:
    - docker
  before_script:
    - cd $SERVICE
    - pip install poetry
    - export PYTHONPATH="$(pwd)/src"
    - poetry install --no-root
  cache:
    key:
      files:
        - $SERVICE/poetry.lock
    paths:
      - /root/.cache/pypoetry
      - /root/.cache/pip
  rules:
    - changes:
        - "**/*.py"
        - ".gitlab-ci.yml"
        - "$SERVICE/poetry.lock"
      when: on_success
    - changes:
        - "**.md"
      when: never
    - when: never

lint_job:
  extends: .base
  stage: linting
  parallel:
    matrix:
      - SERVICE: flow-selection-service
      - SERVICE: scoring-service
      - SERVICE: user-data-service
  script:
    - poetry run ruff check .

mypy_job:
  extends: .base
  stage: type-checking
  parallel:
    matrix:
      - SERVICE: flow-selection-service
      - SERVICE: scoring-service
      - SERVICE: user-data-service
  script:
    - poetry run mypy .

test_job:
  extends: .base
  stage: testing
  parallel:
    matrix:
      - SERVICE: flow-selection-service
      - SERVICE: scoring-service
  script:
    - poetry run pytest -v --tb=short
  coverage: '/TOTAL.*\s+(\d+%)$/'

test_user_data_service:
  extends: .base
  stage: testing_user-data-service
  services:
    - name: postgres:17-alpine
      alias: postgres-test
      variables:
        POSTGRES_USER: ${POSTGRES_TEST_USER}
        POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
        POSTGRES_DB: ${POSTGRES_TEST_DB}
  variables:
    DATABASE_URL: "postgresql+asyncpg://${POSTGRES_TEST_USER}:${POSTGRES_TEST_PASSWORD}@postgres-test:5433/${POSTGRES_TEST_DB}"
  script:
    # Ждём пока PostgreSQL станет готов
    - until pg_isready -h postgres-test -U "$POSTGRES_TEST_USER"; do echo "Waiting for PostgreSQL..."; sleep 1; done
    - poetry run pytest -v --tb=short
  coverage: '/TOTAL.*\s+(\d+%)$/'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"
      when: always
