image: python:3.12-slim

stages:
  - linting
  - type-checking
  - testing

.base:
  tags:
    - docker
  before_script:
    - cd $SERVICE
    - pip install poetry
    - export PYTHONPATH="$(pwd)/src"
    - poetry install --no-root
  cache:
    key:
      files:
        - $SERVICE/poetry.lock
    paths:
      - /root/.cache/pypoetry
      - /root/.cache/pip
  rules:
    - changes:
        - "**/*.py"
        - ".gitlab-ci.yml"
        - "$SERVICE/poetry.lock"
      when: on_success
    - changes:
        - "**.md"
      when: never
    - when: never

lint_job:
  extends: .base
  stage: linting
  parallel:
    matrix:
      - SERVICE: flow_selection_service
      - SERVICE: scoring_service
  script:
    - poetry run ruff check .

mypy_job:
  extends: .base
  stage: type-checking
  parallel:
    matrix:
      - SERVICE: flow_selection_service
      - SERVICE: scoring_service
  script:
    - poetry run mypy .

test_job:
  extends: .base
  stage: testing
  parallel:
    matrix:
      - SERVICE: flow_selection_service
      - SERVICE: scoring_service
  script:
    - poetry run pytest -v --tb=short
  coverage: '/TOTAL.*\s+(\d+%)$/'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"
      when: always
