data_service:
  base_url: "http://localhost:8001"
  timeout: 5
  retries:
    max_attempts: 2
    delay: 1

kafka:
  bootstrap_servers: "localhost:9092"
  topic: "scoring_results"
  session_timeout_ms: 10000
  retry_timeout_ms: 2000
