apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scoring-service.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  {{ .Values.configFileName }}: |
    data_service:
      base_url: "{{ .Values.dataService.baseUrl }}"
      timeout: {{ .Values.dataService.timeout }}
      retries:
        max_attempts: {{ .Values.dataService.retries.maxAttempts }}
        delay: {{ .Values.dataService.retries.delay }}

    kafka:
      bootstrap_servers: "{{ .Values.kafka.bootstrapServers }}"
      topic: "{{ .Values.kafka.topic }}"
      session_timeout_ms: {{ .Values.kafka.sessionTimeoutMs }}
      retry_timeout_ms: {{ .Values.kafka.retryTimeoutMs }}