apiVersion: v1
kind: Service
metadata:
  name: {{ include "scoring-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "scoring-service.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}