apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-lkozlov
  namespace: test
  labels:
    student: lkozlov
    app: user-data-service
data:
  config.k8s.yaml: |
    kafka:
      bootstrap_servers: "infra-kafka.infra.svc.cluster.local:9092"
      topic: "lkozlov_scoring_results"
      session_timeout_ms: 10000
      retry_timeout_ms: 2000