apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-lkozlov
  namespace: test
  labels:
    student: lkozlov
    app: user-data-service
data:
  KAFKA_BOOTSTRAP_SERVERS: "infra-kafka.infra.svc.cluster.local:9092"
  KAFKA_TOPIC: "lkozlov_scoring_results"
  KAFKA_SESSION_TIMEOUT_MS: "10000"
  KAFKA_RETRY_TIMEOUT_MS: "2000"