apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-lkozlov
  namespace: test
  labels:
    student: lkozlov
    app: user-data-service
type: Opaque
stringData:
  POSTGRES_USER: "lkozlov"
  POSTGRES_PASSWORD: "E2Xs6CotCzTLD1uy"
  POSTGRES_DB: "lkozlov"
  POSTGRES_HOST: "postgres-service.infra.svc.cluster.local"
  POSTGRES_PORT: "5432"