apiVersion: v1
kind: Service
metadata:
  name: user-data-service-lkozlov
  namespace: test
  labels:
    student: lkozlov
    app: user-data-service
spec:
  selector:
    app: user-data-service
    student: lkozlov
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP