apiVersion: v1
kind: Service
metadata:
  name: user-data-service-lkozlov
  namespace: test
  labels:
    app: user-data-service
    student: lkozlov
spec:
  type: ClusterIP
  selector:
    app: user-data-service
    student: lkozlov
  ports:
    - name: http
      port: 8001
      targetPort: 8001
