namespace: test
fullnameOverride: "user-data-service-lkozlov"

image:
  repository: shift.gitlab.yandexcloud.net:5050/shift-python/y2025/homeworks/kozlov-l/shift_project/user-data-service
  tag: "latest"
  pullPolicy: Always

service:
  port: 8001
  targetPort: 8001

kafka:
  bootstrapServers: "infra-kafka.infra.svc.cluster.local:9092"
  topic: "lkozlov_scoring_results"
  sessionTimeoutMs: 10000
  retryTimeoutMs: 2000

configFileName: "config.k8s.yaml"

postgresSecretName: "db-credentials-lkozlov"
imagePullSecret: "lkozlov-container-registry"