apiVersion: v1
kind: Service
metadata:
  name: flow-selection-service-lkozlov
  namespace: test
  labels:
    app: flow-selection-service
    student: lkozlov
spec:
  type: ClusterIP
  selector:
    app: flow-selection-service
    student: lkozlov
  ports:
    - name: http
      port: 8000
      targetPort: 8000
