apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-lkozlov
  namespace: test
  labels:
    student: lkozlov
    app: scoring-service
data:
  config.k8s.yaml: |
    data_service:
      base_url: "http://user-data-service-lkozlov:8001"
      timeout: 5
      retries:
        max_attempts: 2
        delay: 1

    kafka:
      bootstrap_servers: "infra-kafka.infra.svc.cluster.local:9092"
      topic: "lkozlov_scoring_results"
      session_timeout_ms: 10000
      retry_timeout_ms: 2000