apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flow-selection-service.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  {{ .Values.configFileName }}: |
    data_service:
      base_url: "{{ .Values.dataService.baseUrl }}"
      timeout: {{ .Values.dataService.timeout }}
      retries:
        max_attempts: {{ .Values.dataService.retries.maxAttempts }}
        delay: {{ .Values.dataService.retries.delay }}

    redis:
      host: "{{ .Values.redis.host }}"
      port: {{ .Values.redis.port }}
      db: {{ .Values.redis.db }}
      ttl: {{ .Values.redis.ttl }}
      password: "{{ .Values.redis.password }}"