apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flow-selection-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "flow-selection-service.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "flow-selection-service.fullname" . }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '{{ .Values.service.targetPort }}'
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: flow-selection-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: CONFIG_FILE
              value: "{{ .Values.configFileName }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://infra-jaeger-collector.infra.svc.cluster.local:4318"
          volumeMounts:
            - name: config-volume
              mountPath: /app/src/{{ .Values.configFileName }}
              subPath: {{ .Values.configFileName }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "flow-selection-service.fullname" . }}-config