namespace: test
fullnameOverride: "scoring-service-lkozlov"

image:
  repository: shift.gitlab.yandexcloud.net:5050/shift-python/y2025/homeworks/kozlov-l/shift_project/scoring-service
  tag: "latest"
  pullPolicy: Always

service:
  port: 8002
  targetPort: 8002

configFileName: "config.k8s.yaml"

kafka:
  bootstrapServers: "infra-kafka.infra.svc.cluster.local:9092"
  topic: "lkozlov_scoring_results"
  sessionTimeoutMs: 10000
  retryTimeoutMs: 2000

dataService:
  baseUrl: "http://user-data-service-lkozlov:8001"
  timeout: 5
  retries:
    maxAttempts: 2
    delay: 1

imagePullSecret: "lkozlov-container-registry"